import axios from "axios";
import {
  AUTHENTICATION_ERROR,
  USER_LOADING,
  USER_LOADED,
  LOGIN_SUCCESSFUL,
  REGISTER_SUCCESSFUL,
  REGISTER_FAILED,
  LOGIN_FAILED,
  LOGOUT_SUCCESSFUL,
} from "../actions/types";
