export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEMS";
export const DELETE_ITEM = "DELETE_ITEM";
export const ADD_DAY = "ADD_DAY";
export const GET_DAYS = "GET_DAYS";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const DELETE_DAY = "DELETE_DAY";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";
export const SIGNUP_SUCCESSFUL = "SIGNUP_SUCCESSFUL";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
